name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Clean & Recreate Android Folder with v2 Embedding
      run: |
        rm -rf android
        flutter create --platforms=android --org com.control.private_voip_app .

    - name: Force Fix SDK to 36 in build.gradle
      run: |
        sed -i 's/compileSdk [0-9]*/compileSdk 36/g' android/app/build.gradle
        sed -i 's/targetSdk [0-9]*/targetSdk 36/g' android/app/build.gradle
        sed -i 's/compileSdkVersion [0-9]*/compileSdkVersion 36/g' android/app/build.gradle

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --no-tree-shake-icons

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
        
